package constants;

import orientation.Block;
import orientation.Tile;

/**
 * Placeholder for the map being used
 * 
 * @author Michael Golfi #260552298
 * @author Paul Albert-Lebrun #260507074
 * 
 */
public class Map {
		
	public static final Tile[][] map1 ={
		   {new Tile(Block.UNOBSTRUCTED, 0, -1, 6),  new Tile(Block.OBSTRUCTED, 1, 0, 6), new Tile(Block.OBSTRUCTED, 2, 1, 6), new Tile(Block.UNOBSTRUCTED, 3, 2, 6), new Tile(Block.UNOBSTRUCTED, 4, 3, 6),  new Tile(Block.UNOBSTRUCTED, 5, 4, 6), new Tile(Block.UNOBSTRUCTED, 6, 5, 6), new Tile(Block.UNOBSTRUCTED, 7, 6, 6)},
		   {new Tile(Block.UNOBSTRUCTED, 8, -1, 5),  new Tile(Block.UNOBSTRUCTED, 9, 0, 5), new Tile(Block.OBSTRUCTED, 10, 1, 5), new Tile(Block.UNOBSTRUCTED, 11, 2, 5), new Tile(Block.UNOBSTRUCTED, 12, 3, 5),  new Tile(Block.UNOBSTRUCTED, 13, 4, 5), new Tile(Block.UNOBSTRUCTED, 14, 5, 5), new Tile(Block.OBSTRUCTED, 15, 6, 5)},
		   {new Tile(Block.OBSTRUCTED, 16, -1, 4),  new Tile(Block.UNOBSTRUCTED, 17, 0, 4), new Tile(Block.UNOBSTRUCTED, 18, 1, 4), new Tile(Block.OBSTRUCTED, 19, 2, 4), new Tile(Block.UNOBSTRUCTED, 20, 3, 4),  new Tile(Block.UNOBSTRUCTED, 21, 4, 4), new Tile(Block.OBSTRUCTED, 22, 5, 4), new Tile(Block.UNOBSTRUCTED, 23, 6, 4)},
		   {new Tile(Block.UNOBSTRUCTED, 24, -1, 3),  new Tile(Block.UNOBSTRUCTED, 25, 0, 3), new Tile(Block.OBSTRUCTED, 26, 1, 3), new Tile(Block.UNOBSTRUCTED, 27, 2, 3), new Tile(Block.UNOBSTRUCTED, 28, 3, 3),  new Tile(Block.UNOBSTRUCTED, 29, 4, 3), new Tile(Block.UNOBSTRUCTED, 30, 5, 3), new Tile(Block.UNOBSTRUCTED, 31, 6, 3)},
		   {new Tile(Block.UNOBSTRUCTED, 32, -1, 2),  new Tile(Block.UNOBSTRUCTED, 33, 0, 2), new Tile(Block.UNOBSTRUCTED, 34, 1, 2), new Tile(Block.UNOBSTRUCTED, 35, 2, 2), new Tile(Block.OBSTRUCTED, 36, 3, 2),  new Tile(Block.UNOBSTRUCTED, 37, 4, 2), new Tile(Block.UNOBSTRUCTED, 38, 5, 2), new Tile(Block.OBSTRUCTED, 39, 6, 2)},
		   {new Tile(Block.UNOBSTRUCTED, 40, -1, 1),  new Tile(Block.UNOBSTRUCTED, 41, 0, 1), new Tile(Block.UNOBSTRUCTED, 42, 1, 1), new Tile(Block.UNOBSTRUCTED, 43, 2, 1), new Tile(Block.OBSTRUCTED, 44, 3, 1),  new Tile(Block.UNOBSTRUCTED, 45, 4, 1), new Tile(Block.OBSTRUCTED, 46, 5, 1), new Tile(Block.OBSTRUCTED, 47, 6, 1)},
		   {new Tile(Block.UNOBSTRUCTED, 48, -1, 0),  new Tile(Block.UNOBSTRUCTED, 49, 0, 0), new Tile(Block.UNOBSTRUCTED, 50, 1, 0), new Tile(Block.UNOBSTRUCTED, 51, 2, 0), new Tile(Block.OBSTRUCTED, 52, 3, 0),  new Tile(Block.UNOBSTRUCTED, 53, 4, 0), new Tile(Block.UNOBSTRUCTED, 54, 5, 0), new Tile(Block.UNOBSTRUCTED, 55, 6, 0)},
		   {new Tile(Block.UNOBSTRUCTED, 56, -1, -1),  new Tile(Block.UNOBSTRUCTED, 57, 0, -1), new Tile(Block.UNOBSTRUCTED, 58, 1, -1), new Tile(Block.UNOBSTRUCTED, 59, 2, -1), new Tile(Block.UNOBSTRUCTED, 60, 3, -1),  new Tile(Block.UNOBSTRUCTED, 61, 4, -1), new Tile(Block.UNOBSTRUCTED, 62, 5, -1), new Tile(Block.OBSTRUCTED, 63, 6, -1)},
		   };
	
	public static final Tile[][] map2 ={
		   {new Tile(Block.UNOBSTRUCTED, 0, -1, 6),  new Tile(Block.UNOBSTRUCTED, 1, 0, 6), new Tile(Block.UNOBSTRUCTED, 2, 1, 6), new Tile(Block.OBSTRUCTED, 3, 2, 6), new Tile(Block.OBSTRUCTED, 4, 3, 6),  new Tile(Block.UNOBSTRUCTED, 5, 4, 6), new Tile(Block.UNOBSTRUCTED, 6, 5, 6), new Tile(Block.OBSTRUCTED, 7, 6, 6)},
		   {new Tile(Block.UNOBSTRUCTED, 8, -1, 5),  new Tile(Block.OBSTRUCTED, 9, 0, 5), new Tile(Block.UNOBSTRUCTED, 10, 1, 5), new Tile(Block.UNOBSTRUCTED, 11, 2, 5), new Tile(Block.OBSTRUCTED, 12, 3, 5),  new Tile(Block.UNOBSTRUCTED, 13, 4, 5), new Tile(Block.UNOBSTRUCTED, 14, 5, 5), new Tile(Block.OBSTRUCTED, 15, 6, 5)},
		   {new Tile(Block.OBSTRUCTED, 16, -1, 4),  new Tile(Block.UNOBSTRUCTED, 17, 0, 4), new Tile(Block.UNOBSTRUCTED, 18, 1, 4), new Tile(Block.UNOBSTRUCTED, 19, 2, 4), new Tile(Block.UNOBSTRUCTED, 20, 3, 4),  new Tile(Block.UNOBSTRUCTED, 21, 4, 4), new Tile(Block.UNOBSTRUCTED, 22, 5, 4), new Tile(Block.UNOBSTRUCTED, 23, 6, 4)},
		   {new Tile(Block.UNOBSTRUCTED, 24, -1, 3),  new Tile(Block.UNOBSTRUCTED, 25, 0, 3), new Tile(Block.OBSTRUCTED, 26, 1, 3), new Tile(Block.UNOBSTRUCTED, 27, 2, 3), new Tile(Block.OBSTRUCTED, 28, 3, 3),  new Tile(Block.UNOBSTRUCTED, 29, 4, 3), new Tile(Block.UNOBSTRUCTED, 30, 5, 3), new Tile(Block.UNOBSTRUCTED, 31, 6, 3)},
		   {new Tile(Block.UNOBSTRUCTED, 32, -1, 2),  new Tile(Block.UNOBSTRUCTED, 33, 0, 2), new Tile(Block.OBSTRUCTED, 34, 1, 2), new Tile(Block.UNOBSTRUCTED, 35, 2, 2), new Tile(Block.UNOBSTRUCTED, 36, 3, 2),  new Tile(Block.UNOBSTRUCTED, 37, 4, 2), new Tile(Block.UNOBSTRUCTED, 38, 5, 2), new Tile(Block.UNOBSTRUCTED, 39, 6, 2)},
		   {new Tile(Block.UNOBSTRUCTED, 40, -1, 1),  new Tile(Block.UNOBSTRUCTED, 41, 0, 1), new Tile(Block.UNOBSTRUCTED, 42, 1, 1), new Tile(Block.UNOBSTRUCTED, 43, 2, 1), new Tile(Block.UNOBSTRUCTED, 44, 3, 1),  new Tile(Block.UNOBSTRUCTED, 45, 4, 1), new Tile(Block.UNOBSTRUCTED, 46, 5, 1), new Tile(Block.UNOBSTRUCTED, 47, 6, 1)},
		   {new Tile(Block.UNOBSTRUCTED, 48, -1, 0),  new Tile(Block.UNOBSTRUCTED, 49, 0, 0), new Tile(Block.UNOBSTRUCTED, 50, 1, 0), new Tile(Block.OBSTRUCTED, 51, 2, 0), new Tile(Block.UNOBSTRUCTED, 52, 3, 0),  new Tile(Block.UNOBSTRUCTED, 53, 4, 0), new Tile(Block.UNOBSTRUCTED, 54, 5, 0), new Tile(Block.OBSTRUCTED, 55, 6, 0)},
		   {new Tile(Block.UNOBSTRUCTED, 56, -1, -1),  new Tile(Block.UNOBSTRUCTED, 57, 0, -1), new Tile(Block.OBSTRUCTED, 58, 1, -1), new Tile(Block.UNOBSTRUCTED, 59, 2, -1), new Tile(Block.UNOBSTRUCTED, 60, 3, -1),  new Tile(Block.OBSTRUCTED, 61, 4, -1), new Tile(Block.UNOBSTRUCTED, 62, 5, -1), new Tile(Block.OBSTRUCTED, 63, 6, -1)},
		   }; 
	
	public static final Tile[][] map3 ={
		   {new Tile(Block.OBSTRUCTED, 0, -1, 6),  new Tile(Block.UNOBSTRUCTED, 1, 0, 6), new Tile(Block.UNOBSTRUCTED, 2, 1, 6), new Tile(Block.UNOBSTRUCTED, 3, 2, 6), new Tile(Block.OBSTRUCTED, 4, 3, 6),  new Tile(Block.UNOBSTRUCTED, 5, 4, 6), new Tile(Block.UNOBSTRUCTED, 6, 5, 6), new Tile(Block.UNOBSTRUCTED, 7, 6, 6)},
		   {new Tile(Block.UNOBSTRUCTED, 8, -1, 5),  new Tile(Block.UNOBSTRUCTED, 9, 0, 5), new Tile(Block.OBSTRUCTED, 10, 1, 5), new Tile(Block.OBSTRUCTED, 11, 2, 5), new Tile(Block.UNOBSTRUCTED, 12, 3, 5),  new Tile(Block.UNOBSTRUCTED, 13, 4, 5), new Tile(Block.UNOBSTRUCTED, 14, 5, 5), new Tile(Block.OBSTRUCTED, 15, 6, 5)},
		   {new Tile(Block.UNOBSTRUCTED, 16, -1, 4),  new Tile(Block.UNOBSTRUCTED, 17, 0, 4), new Tile(Block.UNOBSTRUCTED, 18, 1, 4), new Tile(Block.UNOBSTRUCTED, 19, 2, 4), new Tile(Block.UNOBSTRUCTED, 20, 3, 4),  new Tile(Block.OBSTRUCTED, 21, 4, 4), new Tile(Block.UNOBSTRUCTED, 22, 5, 4), new Tile(Block.UNOBSTRUCTED, 23, 6, 4)},
		   {new Tile(Block.UNOBSTRUCTED, 24, -1, 3),  new Tile(Block.UNOBSTRUCTED, 25, 0, 3), new Tile(Block.UNOBSTRUCTED, 26, 1, 3), new Tile(Block.OBSTRUCTED, 27, 2, 3), new Tile(Block.UNOBSTRUCTED, 28, 3, 3),  new Tile(Block.UNOBSTRUCTED, 29, 4, 3), new Tile(Block.OBSTRUCTED, 30, 5, 3), new Tile(Block.OBSTRUCTED, 31, 6, 3)},
		   {new Tile(Block.UNOBSTRUCTED, 32, -1, 2),  new Tile(Block.UNOBSTRUCTED, 33, 0, 2), new Tile(Block.OBSTRUCTED, 34, 1, 2), new Tile(Block.OBSTRUCTED, 35, 2, 2), new Tile(Block.UNOBSTRUCTED, 36, 3, 2),  new Tile(Block.UNOBSTRUCTED, 37, 4, 2), new Tile(Block.UNOBSTRUCTED, 38, 5, 2), new Tile(Block.UNOBSTRUCTED, 39, 6, 2)},
		   {new Tile(Block.UNOBSTRUCTED, 40, -1, 1),  new Tile(Block.UNOBSTRUCTED, 41, 0, 1), new Tile(Block.UNOBSTRUCTED, 42, 1, 1), new Tile(Block.OBSTRUCTED, 43, 2, 1), new Tile(Block.UNOBSTRUCTED, 44, 3, 1),  new Tile(Block.UNOBSTRUCTED, 45, 4, 1), new Tile(Block.UNOBSTRUCTED, 46, 5, 1), new Tile(Block.UNOBSTRUCTED, 47, 6, 1)},
		   {new Tile(Block.UNOBSTRUCTED, 48, -1, 0),  new Tile(Block.UNOBSTRUCTED, 49, 0, 0), new Tile(Block.UNOBSTRUCTED, 50, 1, 0), new Tile(Block.UNOBSTRUCTED, 51, 2, 0), new Tile(Block.UNOBSTRUCTED, 52, 3, 0),  new Tile(Block.UNOBSTRUCTED, 53, 4, 0), new Tile(Block.UNOBSTRUCTED, 54, 5, 0), new Tile(Block.UNOBSTRUCTED, 55, 6, 0)},
		   {new Tile(Block.UNOBSTRUCTED, 56, -1, -1),  new Tile(Block.UNOBSTRUCTED, 57, 0, -1), new Tile(Block.UNOBSTRUCTED, 58, 1, -1), new Tile(Block.UNOBSTRUCTED, 59, 2, -1), new Tile(Block.OBSTRUCTED, 60, 3, -1),  new Tile(Block.OBSTRUCTED, 61, 4, -1), new Tile(Block.UNOBSTRUCTED, 62, 5, -1), new Tile(Block.OBSTRUCTED, 63, 6, -1)},
		   }; 
	
	/*public static final Tile[][] map4  ={
		{new Tile(Block.OBSTRUCTED, 0, -1, 10),  new Tile(Block.UNOBSTRUCTED, 1, 0, 10), new Tile(Block.UNOBSTRUCTED, 2, 1, 10), new Tile(Block.UNOBSTRUCTED, 3, 2, 10), new Tile(Block.OBSTRUCTED, 4, 3, 10),  new Tile(Block.UNOBSTRUCTED, 5, 4, 10), new Tile(Block.UNOBSTRUCTED, 6, 5, 10), new Tile(Block.UNOBSTRUCTED, 7, 6, 10), new Tile(Block.OBSTRUCTED, 4, 3, 10),  new Tile(Block.UNOBSTRUCTED, 5, 4, 10), new Tile(Block.UNOBSTRUCTED, 6, 5, 10), new Tile(Block.UNOBSTRUCTED, 7, 6, 10)},
		{new Tile(Block.UNOBSTRUCTED, 12, -1, 9),  new Tile(Block.UNOBSTRUCTED, 13, 0, 9), new Tile(Block.OBSTRUCTED, 14, 1, 9), new Tile(Block.OBSTRUCTED, 15, 2, 9), new Tile(Block.UNOBSTRUCTED, 16, 3, 9),  new Tile(Block.UNOBSTRUCTED, 13, 4, 9), new Tile(Block.UNOBSTRUCTED, 14, 5, 9), new Tile(Block.OBSTRUCTED, 15, 6, 9), new Tile(Block.OBSTRUCTED, 4, 3, 9),  new Tile(Block.UNOBSTRUCTED, 5, 4, 9), new Tile(Block.UNOBSTRUCTED, 6, 5, 9), new Tile(Block.UNOBSTRUCTED, 7, 6, 9)},
		{new Tile(Block.UNOBSTRUCTED, 24, -1, 8),  new Tile(Block.UNOBSTRUCTED, 25, 0, 8), new Tile(Block.UNOBSTRUCTED, 26, 1, 8), new Tile(Block.UNOBSTRUCTED, 27, 2, 8), new Tile(Block.UNOBSTRUCTED, 28, 3, 8),  new Tile(Block.OBSTRUCTED, 21, 4, 8), new Tile(Block.UNOBSTRUCTED, 22, 5, 8), new Tile(Block.UNOBSTRUCTED, 23, 6, 8), new Tile(Block.OBSTRUCTED, 4, 3, 8),  new Tile(Block.UNOBSTRUCTED, 5, 4, 8), new Tile(Block.UNOBSTRUCTED, 6, 5, 8), new Tile(Block.UNOBSTRUCTED, 7, 6, 8)},
		{new Tile(Block.UNOBSTRUCTED, 36, -1, 7),  new Tile(Block.UNOBSTRUCTED, 37, 0, 7), new Tile(Block.UNOBSTRUCTED, 38, 1, 7), new Tile(Block.OBSTRUCTED, 39, 2, 7), new Tile(Block.UNOBSTRUCTED, 40, 3, 7),  new Tile(Block.UNOBSTRUCTED, 29, 4, 7), new Tile(Block.OBSTRUCTED, 30, 5, 7), new Tile(Block.OBSTRUCTED, 31, 6, 7), new Tile(Block.OBSTRUCTED, 4, 3, 7),  new Tile(Block.UNOBSTRUCTED, 5, 4, 7), new Tile(Block.UNOBSTRUCTED, 6, 5, 7), new Tile(Block.UNOBSTRUCTED, 7, 6, 7)},
		{new Tile(Block.UNOBSTRUCTED, 48, -1, 6),  new Tile(Block.UNOBSTRUCTED, 49, 0, 6), new Tile(Block.OBSTRUCTED, 50, 1, 6), new Tile(Block.OBSTRUCTED, 51, 2, 6), new Tile(Block.UNOBSTRUCTED, 52, 3, 6),  new Tile(Block.UNOBSTRUCTED, 37, 4, 6), new Tile(Block.UNOBSTRUCTED, 38, 5, 6), new Tile(Block.UNOBSTRUCTED, 39, 6, 6), new Tile(Block.OBSTRUCTED, 4, 3, 6),  new Tile(Block.UNOBSTRUCTED, 5, 4, 6), new Tile(Block.UNOBSTRUCTED, 6, 5, 6), new Tile(Block.UNOBSTRUCTED, 7, 6, 6)},
		{new Tile(Block.UNOBSTRUCTED, 60, -1, 5),  new Tile(Block.UNOBSTRUCTED, 61, 0, 5), new Tile(Block.UNOBSTRUCTED, 62, 1, 5), new Tile(Block.OBSTRUCTED, 63, 2, 5), new Tile(Block.UNOBSTRUCTED, 64, 3, 5),  new Tile(Block.UNOBSTRUCTED, 45, 4, 5), new Tile(Block.UNOBSTRUCTED, 46, 5, 5), new Tile(Block.UNOBSTRUCTED, 47, 6, 5), new Tile(Block.OBSTRUCTED, 4, 3, 5),  new Tile(Block.UNOBSTRUCTED, 5, 4, 5), new Tile(Block.UNOBSTRUCTED, 6, 5, 5), new Tile(Block.UNOBSTRUCTED, 7, 6, 5)},
		{new Tile(Block.UNOBSTRUCTED, 72, -1, 4),  new Tile(Block.UNOBSTRUCTED, 73, 0, 4), new Tile(Block.UNOBSTRUCTED, 74, 1, 4), new Tile(Block.UNOBSTRUCTED, 75, 2, 4), new Tile(Block.UNOBSTRUCTED, 76, 3, 4),  new Tile(Block.UNOBSTRUCTED, 53, 4, 4), new Tile(Block.UNOBSTRUCTED, 54, 5, 4), new Tile(Block.UNOBSTRUCTED, 55, 6, 4), new Tile(Block.OBSTRUCTED, 4, 3, 4),  new Tile(Block.UNOBSTRUCTED, 5, 4, 4), new Tile(Block.UNOBSTRUCTED, 6, 5, 4), new Tile(Block.UNOBSTRUCTED, 7, 6, 4)},
		{new Tile(Block.UNOBSTRUCTED, 84, -1, 3),  new Tile(Block.UNOBSTRUCTED, 85, 0, 3), new Tile(Block.UNOBSTRUCTED, 86, 1, 3), new Tile(Block.UNOBSTRUCTED, 87, 2, 3), new Tile(Block.OBSTRUCTED, 88, 3, 3),  new Tile(Block.OBSTRUCTED, 61, 4, 3), new Tile(Block.UNOBSTRUCTED, 62, 5, 3), new Tile(Block.OBSTRUCTED, 63, 6, -3), new Tile(Block.OBSTRUCTED, 4, 3, 3),  new Tile(Block.UNOBSTRUCTED, 5, 4, 3), new Tile(Block.UNOBSTRUCTED, 6, 5, 3), new Tile(Block.UNOBSTRUCTED, 7, 6, 3)},
		{new Tile(Block.UNOBSTRUCTED, 96, -1, 2),  new Tile(Block.UNOBSTRUCTED, 97, 0, 2), new Tile(Block.OBSTRUCTED, 98, 1, 2), new Tile(Block.OBSTRUCTED, 99, 2, 2), new Tile(Block.UNOBSTRUCTED, 100, 3, 2),  new Tile(Block.UNOBSTRUCTED, 37, 4, 2), new Tile(Block.UNOBSTRUCTED, 38, 5, 2), new Tile(Block.UNOBSTRUCTED, 39, 6, 2), new Tile(Block.OBSTRUCTED, 4, 3, 2),  new Tile(Block.UNOBSTRUCTED, 5, 4, 2), new Tile(Block.UNOBSTRUCTED, 6, 5, 2), new Tile(Block.UNOBSTRUCTED, 7, 6, 2)},
		{new Tile(Block.UNOBSTRUCTED, 108, -1, 1),  new Tile(Block.UNOBSTRUCTED, 109, 0, 1), new Tile(Block.UNOBSTRUCTED, 110, 1, 1), new Tile(Block.OBSTRUCTED, 111, 2, 1), new Tile(Block.UNOBSTRUCTED, 112, 3, 1),  new Tile(Block.UNOBSTRUCTED, 45, 4, 1), new Tile(Block.UNOBSTRUCTED, 46, 5, 1), new Tile(Block.UNOBSTRUCTED, 47, 6, 1), new Tile(Block.OBSTRUCTED, 4, 3, 1),  new Tile(Block.UNOBSTRUCTED, 5, 4, 1), new Tile(Block.UNOBSTRUCTED, 6, 5, 1), new Tile(Block.UNOBSTRUCTED, 7, 6, 1)},
		{new Tile(Block.UNOBSTRUCTED, 120, -1, 0),  new Tile(Block.UNOBSTRUCTED, 121, 0, 0), new Tile(Block.UNOBSTRUCTED, 122, 1, 0), new Tile(Block.UNOBSTRUCTED, 123, 2, 0), new Tile(Block.UNOBSTRUCTED, 124, 3, 0),  new Tile(Block.UNOBSTRUCTED, 53, 4, 0), new Tile(Block.UNOBSTRUCTED, 54, 5, 0), new Tile(Block.UNOBSTRUCTED, 55, 6, 0), new Tile(Block.OBSTRUCTED, 4, 3, 0),  new Tile(Block.UNOBSTRUCTED, 5, 4, 0), new Tile(Block.UNOBSTRUCTED, 6, 5, 0), new Tile(Block.UNOBSTRUCTED, 7, 6, 0)},
		{new Tile(Block.UNOBSTRUCTED, 132, -1, -1),  new Tile(Block.UNOBSTRUCTED, 133, 0, -1), new Tile(Block.UNOBSTRUCTED, 134, 1, -1), new Tile(Block.UNOBSTRUCTED, 135, 2, -1), new Tile(Block.OBSTRUCTED, 136, 3, -1),  new Tile(Block.OBSTRUCTED, 61, 4, -1), new Tile(Block.UNOBSTRUCTED, 62, 5, -1), new Tile(Block.OBSTRUCTED, 63, 6, -1), new Tile(Block.OBSTRUCTED, 4, 3, -1),  new Tile(Block.UNOBSTRUCTED, 5, 4, -1), new Tile(Block.UNOBSTRUCTED, 6, 5, -1), new Tile(Block.UNOBSTRUCTED, 7, 6, -1)},
		}; 
	}*/
	
}
